# 应用服务 WEB 访问端口
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名与下划线命名的自动转换


server:
  port: 8080

swagger2:
  enable: true
